client:
  keystorePathValidCerts: "../testDataTemplates/certificates/ecc/fachmodul_clientCerts/valid"
  keystorePathAlternativeCerts: "../testDataTemplates/certificates/ecc/fachmodul_clientCerts/valid-alternative"
  keystorePathInvalidCerts: "../testDataTemplates/certificates/ecc/fachmodul_clientCerts/invalid"

testObject:
  name: "Server 0815"
  type: "TlsServer"
  ipAddressOrFqdn: "127.0.0.1"
  port: 8443
  ocspGracePeriodSeconds: 0
  tslDownloadIntervalSeconds: 2
  tslProcessingTimeSeconds: 2

ocspResponder:
  ipAddressOrFqdn: "127.0.0.1"
  port: 8083

tslProvider:
  ipAddressOrFqdn: "127.0.0.1"
  port: 8084
